apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __APP_NAME__-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: local-path
  volumeMode: Filesystem
